### ISSUE TITLE
acpi error

### ISSUE THREAD

**Issue by hello-sucess** [H3C4T0M8/Hackintosh-Gigabyte-z690-UD-DDR4-OpenCore#2]
Hello, my motherboard is also Gigabyte-z690-UD-DDR4, 6600xt, but I use this efi to prompt acpi warning: unsupported....,

**Comment by H3C4T0M8** [comment]
I am at Moment at work. Can you make a photo from screen and upload it to a side + send me a link?

**Comment by hello-sucess** [comment]
![hpg](https://user-images.githubusercontent.com/31380144/174993076-29d0864e-b67c-479d-846b-ed1309b86fb5.jpg)

**Comment by H3C4T0M8** [comment]
I will check what we can do in some hours. Thanks to send the picture

**Comment by hello-sucess** [comment]
Thank you so much

**Comment by H3C4T0M8** [comment]
https://files.fm/u/pfys4vbmh test this

**Comment by hello-sucess** [comment]
Still doesn't work, but I have resolved the acpi error, but a new error appears

**Comment by hello-sucess** [comment]
![image](https://user-images.githubusercontent.com/31380144/175256309-44594478-8da1-4de9-a0a2-b051b14c47c6.png)

**Comment by hello-sucess** [comment]
![image](https://user-images.githubusercontent.com/31380144/175257733-6e79b6a6-0e0c-4a5d-ae34-06e866b8904c.png)

**Comment by H3C4T0M8** [comment]
You have setup your bios settings correctly? to use it for Hackintosh I mean.
what cpu you use exactly?

**Comment by H3C4T0M8** [comment]
https://files.fm/u/zugg8r68z test pls

**Comment by hello-sucess** [comment]
[GIGABYTE-Z690I-Hackintosh-master 2.zip](https://github.com/H3C4T0M8/Hackintosh-Gigabyte-z690-UD-DDR4-OpenCore/files/8968284/GIGABYTE-Z690I-Hackintosh-master.2.zip)


The bios is correct, I can enter normally with other efi, my cpu is i7-12700k. The efi that can enter the system normally is this. But not sleeping

**Comment by hello-sucess** [comment]
![image](https://user-images.githubusercontent.com/31380144/175326628-617c5a5f-e71f-4c7f-9f38-56a0fbae8a5b.png)

**Comment by H3C4T0M8** [comment]
What you try to install? When you like to install big Sur + it don't work.
First you need to install Catalina or widows, to make a usbmapping. Without you usb device get lost by port disconnect.

You can do the mapping in Windows, or add usbinjectall kext and activate portlimit to boot into Catalina.

Ah you have a efi that work? We will fix the problem with sleep.

**Comment by H3C4T0M8** [comment]
> 
> 
> [GIGABYTE-Z690I-Hackintosh-master 2.zip](https://github.com/H3C4T0M8/Hackintosh-Gigabyte-z690-UD-DDR4-OpenCore/files/8968284/GIGABYTE-Z690I-Hackintosh-master.2.zip)
> 
> 
> 
> 
> 
> The bios is correct, I can enter normally with other efi, my cpu is i7-12700k. The efi that can enter the system normally is this. But not sleeping

You use gpu at this hackintosh, right?
Can you send me all Infos about your computer components? gpu, WLAN - Bluetooth, and settings from os (energy and sleep settings) 
I think I know what we can do to solve it

I go to bed now... good night

**Comment by hello-sucess** [comment]
[EFI.zip](https://github.com/H3C4T0M8/Hackintosh-Gigabyte-z690-UD-DDR4-OpenCore/files/8972961/EFI.zip)

Good night, this is the EFI I am currently using, I am going to Windows to export a copy of my configuration table.

**Comment by hello-sucess** [comment]
Processor 12th Gen Intel Core i7-12700K
  Motherboard Gigabyte Z690 UD DDR4 (LPC Controller/eSPI Controller - 7A84)
  Graphics AMD Radeon RX 6600 XT ( 7890 MB / Sapphire )
  Memory 32GB (Kingston DDR4 3200MHz 16GB x 2)
  Primary Hard Drive Western Digital WD_BLACK SN750 2TB (2 TB / SSD)
  Monitor Philips PHLC19B PHL 275M7C (27 inches)
  Sound Card Realtek @ Intel High Definition Audio Controller
  Network Card Realtek Realtek PCIe 2.5 GbE Series Controller / GIGABYTE

**Comment by hello-sucess** [comment]
WLAN - Bluetooth      BCM94360CD

**Comment by H3C4T0M8** [comment]
Can you make the usb mapping in windows or macOS too? you can use this tool for mapping https://github.com/USBToolBox/tool/releases or the other tool too https://github.com/corpnewt/USBMap . use a usb2.0 and usb3.x Stick in each usbport 

When the computer go into sleep...what happened ? the computer wake up directly, or from time to time? or what problem you have exactly?

**Comment by hello-sucess** [comment]
[UTBMap.kext.zip](https://github.com/H3C4T0M8/Hackintosh-Gigabyte-z690-UD-DDR4-OpenCore/files/8973576/UTBMap.kext.zip)
![image](https://user-images.githubusercontent.com/31380144/175472791-cce5fb82-735f-4ba3-8449-e952f09f0959.png)
Can't wake up after sleep. Just restart the computer

**Comment by hello-sucess** [comment]
I have reduced the ports in this kext to less than 15, and deleted the unlinked ports.

**Comment by H3C4T0M8** [comment]
your hack don't show a screen when he wakeup? so you need to push the power button to restart your computer? or the computer make the restart byself? when you disconnect the hdmi and connect it, you get a screen?

**Comment by hello-sucess** [comment]
After reconnecting the dp monitor, there is no response, and it cannot be woken up after sleep, and can only be restarted.

**Comment by H3C4T0M8** [comment]
hmmm.thats interesting. but you use a gpu, and no igpu, or not??? normally it need to wakeup with screen with gpu

**Comment by hello-sucess** [comment]
Cannot drive the 12th generation cpu core display

**Comment by H3C4T0M8** [comment]
so you have disable it in bios...only gpu selected?

**Comment by hello-sucess** [comment]
Not disabling nuclear display in bios

**Comment by H3C4T0M8** [comment]
[EFI-8.zip](https://github.com/H3C4T0M8/Hackintosh-Gigabyte-z690-UD-DDR4-OpenCore/files/8973859/EFI-8.zip)

ok...I need to check some patches. ah, the one patch in your efi was useless. maybe it was because the patch idk. the ssd was missed

**Comment by H3C4T0M8** [comment]
you use a 4k display?

**Comment by hello-sucess** [comment]
use 2k display.  
After using this efi, the esp disk cannot be written, and the write display space is insufficient. But the esp disk has enough space.

**Comment by hello-sucess** [comment]
sorry,I forgot to delete the recycle bin, this is my problem. .

**Comment by H3C4T0M8** [comment]
you need to delete the files in waste... sorry for my bad English XD

**Comment by hello-sucess** [comment]
Test sleep still doesn't work.

**Comment by H3C4T0M8** [comment]
ok...one moment
[EFI-8 2.zip](https://github.com/H3C4T0M8/Hackintosh-Gigabyte-z690-UD-DDR4-OpenCore/files/8974081/EFI-8.2.zip)

try please

you use Monterey ? you have make the power managment file byself?

**Comment by hello-sucess** [comment]
yes,No power management files were made

**Comment by H3C4T0M8** [comment]
ok...one Moment

**Comment by H3C4T0M8** [comment]
https://github.com/corpnewt/CPUFriendFriend to make the cpu powermanagment (idk what cpu the guy before have create...he got the same cpu, same like your?
and here the other script https://github.com/corpnewt/SSDTTime

And you need to test other cable and ports pls
Note: Some Navi 21 cards currently require the boot argument agdpmod=pikera to get a display out. 
You have a Navi 23 series
you know if you need this boot arg really?


CSM in bios disabled?

**Comment by hello-sucess** [comment]
I tried turning off agdpmod=pikera, here is my dsdt
CSM IS DISABLED.
[patches_Clover.zip](https://github.com/H3C4T0M8/Hackintosh-Gigabyte-z690-UD-DDR4-OpenCore/files/8974649/patches_Clover.zip)

**Comment by H3C4T0M8** [comment]
you use hdmi or DisplayPort ?

**Comment by hello-sucess** [comment]
DisplayPort

**Comment by H3C4T0M8** [comment]
you have try with hdmi already?

**Comment by hello-sucess** [comment]
Haven't tried it yet, I'll try it now

**Comment by hello-sucess** [comment]
hdmi still fails

**Comment by H3C4T0M8** [comment]
ok. we can look tomorrow. you have check if you have this problem with Ventura too?

**Comment by hello-sucess** [comment]
Haven't tested Ventura

**Comment by H3C4T0M8** [comment]
Ok. I search tomorrow for fix... And will ask the www.hackintosh-forum.de guys too

**Comment by hello-sucess** [comment]
Thanks a lot, I'll try bigsur

**Comment by H3C4T0M8** [comment]
Someone from forum say, this problem is not the configuration from bootloader... It's a problem from graphic card bios. The power play table settings.

Maybe we can find a other bios in web🤷‍♂️ I don't know

**Comment by hello-sucess** [comment]
I switch to sapphire 6600xt bios

**Comment by H3C4T0M8** [comment]
Any News?

**Comment by hello-sucess** [comment]
I found out that the voltage I helped me was broken, and after the low voltage would supply power, I did the same at the window and gave me a replacement. Trying to sleep on the mac.

**Comment by hello-sucess** [comment]
[EFI.zip](https://github.com/H3C4T0M8/Hackintosh-Gigabyte-z690-UD-DDR4-OpenCore/files/9000081/EFI.zip)

I solved the problem with XDCI CNVW, but there are two more that I don't know what's going on. usb has been customized.
error: kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: RP09 RP05

**Comment by H3C4T0M8** [comment]
send me a picture from Hackintool, from pcie ...need to know the aspm from this 2 devices

https://dortania.github.io/OpenCore-Install-Guide/clover-conversion/Clover-config.html

My Laptop soon without energy, sorry
DisableASPM:

DeviceProperties -> Add -> PciRoot... -> pci-aspm-default | Data | <00>

you need to search to give this 2 devices maybe energy in sleep via device property

**Comment by hello-sucess** [comment]
<img width="2453" alt="image" src="https://user-images.githubusercontent.com/31380144/176167390-c6ffb6b8-ae4d-49b9-be82-2d1d1e7d1538.png">

**Comment by hello-sucess** [comment]
I tried setting pci-aspm-default on some pic devices, but didn't find RP09 RP05

**Comment by H3C4T0M8** [comment]
Yes. I remember to have see already ssdt files with this device in the name from ssdt. But where I have see this files... Hmm

**Comment by hello-sucess** [comment]
[dsdt.zip](https://github.com/H3C4T0M8/Hackintosh-Gigabyte-z690-UD-DDR4-OpenCore/files/9000988/dsdt.zip)

**Comment by H3C4T0M8** [comment]
https://www.hackintosh-forum.de/forum/thread/40089-wie-kann-ich-den-patch-code-in-dsdt-einfügen/

**Comment by hello-sucess** [comment]
Thank you very much, but I don't know how to operate, do I need to block these two pci?

**Comment by H3C4T0M8** [comment]
No. I think this devices got power lost in sleep... 
Because this I asked for picture from hackintool.

You have aspm options in bios menu? I have it at my msi board in bios.

https://www.tonymacx86.com/threads/z490-z590-will-z590-ever-have-macos-support.308084/page-109

You have thunderbolt?

Yes, I think it's thunderbolt device

https://www.tonymacx86.com/threads/in-progress-ssdt-for-thunderbolt-3-hotplug.248784/

**Comment by hello-sucess** [comment]
I don't see a configuration about thunderbolts in the bios. But I do have an interface like this.

**Comment by hello-sucess** [comment]
SuperSpeed USB 3.2 Gen 2x2 TYPE-C® delivers up to 20Gb/s transfer speeds

**Comment by hello-sucess** [comment]
But there is "platform power management" in bios

**Comment by hello-sucess** [comment]
![image](https://user-images.githubusercontent.com/31380144/176220336-5aeb8b92-2c52-4b67-96c8-d894e2159361.png)

**Comment by hello-sucess** [comment]
I successfully solved RP09/RP05, but new error appeared, RP08=>BCM4360 802.11ac

**Comment by hello-sucess** [comment]
Now only the xdci problem is left. xdci is my usb controller. I modified dsdt and changed _PRW to XPRW, and it can sleep successfully, but after powering on, it can only wake up from sleep once, and it will restart the second time. And can only wake up with the power button. I am going to re-customize the usb

**Comment by H3C4T0M8** [comment]
You can make a account at http://osxlatitude.com and ask there. There are 3 peoples who know how to fix ssdt thinks.

**Comment by hello-sucess** [comment]
Thank you very much, because my bluetooth is on the usb-hub, this is currently unsolved, but it can be woken up with the power button.

**Comment by H3C4T0M8** [comment]
The hackintosh don't wake-up without pressing power button because the ssdt + patch that you use in your efi. With this patch only with power button😉

**Comment by hello-sucess** [comment]
Yes, I have tried my own custom solution, but the last step bluetooth doesn't work. This should be the best solution so far.

**Comment by H3C4T0M8** [comment]
you fixed your problems now?

if not than send me your current efi + export in Hackintool ( at PCIe ) the info (you can safe it in Hackintool to 3 or 4 files. 
and I need from [ ](https://github.com/acidanthera/IOJones/releases) a file. (only open it and safe to file) pls

**Comment by hello-sucess** [comment]
I solved the hug sleep problem, the performance is not optimized, only multi-core but more than 8000 points, and my microphone will cause seconds to wake up. After I modify it, I will send you a copy of my efi. By the way, is there any good solution for only disabling one usb port to wake up?

**Comment by H3C4T0M8** [comment]
disabling one usb to wake up? hmmm. maybe with ssdt, I don't know. but why you ask? because you can't wake the computer without push the power button?

https://github.com/RehabMan/Laptop-DSDT-Patch/blob/master/usb/usb_prw_0x0d_xhc_skl.txt

https://github.com/RehabMan/Laptop-DSDT-Patch/tree/master/usb

**Comment by hello-sucess** [comment]
Because I have a usb device (headphone) which causes sleep to wake up in seconds.

**Comment by H3C4T0M8** [comment]
maybe the mapping not perfect? change it to other usb and test. or make usb 2.0 port for it.

or check this...maybe it help
https://github.com/5T33Z0/OC-Little-Translated/blob/main/04_Fixing_Sleep_and_Wake_Issues/060D_Instant_Wake_Fix/i%20Common%20060D%20Patch/README.md

can you show me Hackintool the usb section. like to check if you have the mapping correctly

**Comment by hello-sucess** [comment]
The same is true when I change the usb. This is my interface problem. I am going to buy one and then convert the pci to the usb, plug the microphone in, and prohibit the pci from waking up the device.

**Comment by hello-sucess** [comment]
This patch will make all usb ports unable to wake up.
